video:
  resolution: 1080p
  mime_type: video/mp4

directory:
  videos: data/videos
  photos: data/photos
  faces: data/faces

path:
  cnn_face_model: models/cnn-face-model/mmod_human_face_detector.dat