video:
  resolution: 1080p
  mime_type: video/mp4

directory:
  videos: data/videos
  photos: data/photos
  faces: data/faces

path:
  cnn_face_model: models/cnn-face-model/mmod_human_face_detector.dat
  face_landmarks_model: models/face-landmark-model/shape_predictor_68_face_landmarks.dat